version: '3.8'

services:
  mssql:
    tty: true
    build: .
    container_name: dev
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: '${SA_PASSWORD}'
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      USER_NAME: '${USER_NAME}'
      USER_PASSWORD: '${USER_PASSWORD}'
      DB_NAME: '${DB_NAME}'
    volumes:
      - mssql_data:/var/opt/mssql
    env_file:
      - .env

volumes:
  mssql_data:
