CREATE DATABASE ${DB_NAME};
GO

USE ${DB_NAME};
GO

CREATE LOGIN ${USER_NAME} WITH PASSWORD = '${USER_PASSWORD}';
GO

CREATE USER ${USER_NAME} FOR LOGIN ${USER_NAME};
GO

ALTER SERVER ROLE sysadmin ADD MEMBER [${USER_NAME}];
GO